import Foundation

/// Emits an R script that reproduces a notebook's steps.
///
/// This is what the value-typed step was for. A step describes an analysis
/// rather than performing one, so the same value the native kernel runs can be
/// written out as code — and the script is where the long tail lives. No
/// statistics package covers every diagnostic; past a point the honest answer
/// is to hand the user a script and a console rather than keep reimplementing
/// R badly.
///
/// One way only. Nothing parses R's output back into a result: that would mean
/// owning a fragile contract with another program's formatting, and the console
/// is already where the output belongs.
nonisolated enum NotebookScript {

    /// Cell delimiter, as Jupyter and Positron use it. The editor sends the
    /// enclosing cell to the console, so this is the unit a user runs.
    static let cellMarker = "# %%"

    /// A table the script reads, as a path relative to the project root.
    struct Source: Hashable, Sendable {
        let frame: String
        let path: String
    }

    static func r(steps: [AnalysisStep], missingCodes: [String], sources: [String: Source]) -> String {
        var output = "\(Self.cellMarker) Setup\n"
        output += "# Generated by TypeNBash. Run from the project root.\n"
        output += "# Cells are delimited by \"\(Self.cellMarker)\"; send one to the console to run it.\n"
        output += "#\n"
        output += "# This reproduces the notebook's steps and is meant to be edited. Note that R\n"
        output += "# coerces a non-numeric cell to NA, where the notebook counts \"missing\" and\n"
        output += "# \"unusable\" apart, so an N here can differ from the one in the pane.\n\n"
        let codes = ([""] + missingCodes).map { "\"\($0)\"" }.joined(separator: ", ")
        output += "missing <- c(\(codes))\n"
        for source in Set(sources.values).sorted(by: { $0.frame < $1.frame }) {
            output += "\(source.frame) <- read.csv(\(Self.quote(source.path)), check.names = FALSE, na.strings = missing)\n"
        }

        // A notebook with no steps still earns a script: someone who wants to
        // write R against a table should not have to build steps they do not
        // want first. Give them the frame loaded and somewhere to start.
        guard !steps.isEmpty else {
            let frame = sources[""]?.frame ?? sources.values.first?.frame ?? "data1"
            output += "\n\(Self.cellMarker) 1. Explore\n"
            output += "# The notebook had no steps, so this loads the table and stops.\n"
            output += "# Write cells below, or add steps in the notebook and generate again.\n"
            output += "dim(\(frame))\n"
            output += "str(\(frame), list.len = 25)\n"
            return output
        }

        for (position, step) in steps.enumerated() {
            guard let source = sources[step.dataset] else { continue }
            output += "\n\(Self.cellMarker) \(position + 1). \(step.title)\n"
            let terms = Self.terms(of: step)
            output += Self.frame(terms, from: source.frame)
            output += Self.body(step, terms: terms)
        }
        return output
    }

    // MARK: Columns

    /// A column as the script refers to it: a safe R identifier, the position it
    /// reads from, and whether this step uses it as a number.
    private struct Term {
        let name: String
        let index: Int
        let isNumeric: Bool
    }

    private static func terms(of step: AnalysisStep) -> [Term] {
        let columns = step.columns
        let numeric: [Bool] = switch step.operation {
            case .describe, .correlation, .oneSampleT, .pairedT:
                columns.map { _ in true }
            case .frequency, .crossTabulation, .chiSquareIndependence:
                columns.map { _ in false }
            case .independentT, .oneWayANOVA:
                [true] + columns.dropFirst().map { _ in false }
            case .linearRegression(_, let predictors):
                [true] + predictors.map { !$0.isCategorical }
        }
        var used: Set<String> = []
        return zip(columns, numeric).map { column, isNumeric in
            let base = Self.identifier(column.label, fallback: column.index)
            var name = base
            var suffix = 2
            while used.contains(name) {
                name = "\(base)_\(suffix)"
                suffix += 1
            }
            used.insert(name)
            return Term(name: name, index: column.index, isNumeric: isNumeric)
        }
    }

    /// Headers can be blank, repeated or full of punctuation, which is why the
    /// notebook addresses columns by position. The script keeps that: it reads
    /// by index and names the result itself, so no header can produce invalid R.
    private static func identifier(_ label: String, fallback index: Int) -> String {
        var result = ""
        for character in label {
            if character.isLetter || character.isNumber {
                result.append(character)
            } else if !result.isEmpty, result.last != "_" {
                result.append("_")
            }
        }
        while result.last == "_" { result.removeLast() }
        guard let first = result.first, first.isLetter else { return "col\(index + 1)" }
        return result
    }

    private static func frame(_ terms: [Term], from source: String) -> String {
        let assignments = terms.map { term in
            let read = "\(source)[[\(term.index + 1)]]"
            return "  \(term.name) = \(term.isNumeric ? "as.numeric(\(read))" : "as.character(\(read))")"
        }
        return "d <- data.frame(\n" + assignments.joined(separator: ",\n")
            + ",\n  stringsAsFactors = FALSE\n)\n"
    }

    // MARK: Analyses

    private static func body(_ step: AnalysisStep, terms: [Term]) -> String {
        let names = terms.map(\.name)
        switch step.operation {
            case .describe:
                return """
                print(summary(d))
                print(sapply(d, function(v) c(n = sum(!is.na(v)), mean = mean(v, na.rm = TRUE),
                                              sd = sd(v, na.rm = TRUE))))

                """
            case .frequency:
                return """
                counts <- table(d$\(names[0]), useNA = "no")
                print(counts)
                print(round(100 * prop.table(counts), 2))

                """
            case .crossTabulation:
                return """
                print(addmargins(table(d$\(names[0]), d$\(names[1]))))

                """
            case .chiSquareIndependence:
                return """
                tab <- table(d$\(names[0]), d$\(names[1]))
                print(addmargins(tab))
                print(chisq.test(tab, correct = FALSE))

                """
            case .correlation(_, let method):
                let name = Self.quote(method.rawValue.lowercased())
                let use = Self.quote(step.missing == .listwise ? "complete.obs" : "pairwise.complete.obs")
                let adjustment = switch step.adjustment {
                    case .none: "none"
                    case .holm: "holm"
                    case .benjaminiHochberg: "BH"
                }
                return """
                print(cor(d, method = \(name), use = \(use)))
                pairs <- combn(names(d), 2)
                for (i in seq_len(ncol(pairs))) {
                  cat("\\n--", pairs[1, i], "x", pairs[2, i], "--\\n")
                  print(cor.test(d[[pairs[1, i]]], d[[pairs[2, i]]], method = \(name)))
                }
                raw <- apply(pairs, 2, function(p)
                  cor.test(d[[p[1]]], d[[p[2]]], method = \(name))$p.value)
                print(data.frame(a = pairs[1, ], b = pairs[2, ], p = raw,
                                 adjusted = p.adjust(raw, \(Self.quote(adjustment)))))

                """
            case .oneSampleT(_, let value):
                return """
                print(t.test(d$\(names[0]), mu = \(value)))

                """
            case .independentT(_, _, let variance):
                return """
                print(t.test(\(names[0]) ~ \(names[1]), data = d, var.equal = \(variance == .pooled ? "TRUE" : "FALSE")))
                # Levene's test needs the car package:
                # car::leveneTest(\(names[0]) ~ factor(\(names[1])), data = d)

                """
            case .pairedT:
                return """
                print(t.test(d$\(names[0]), d$\(names[1]), paired = TRUE))

                """
            case .oneWayANOVA:
                return """
                model <- aov(\(names[0]) ~ factor(\(names[1])), data = d)
                print(summary(model))

                """
            case .linearRegression(_, let predictors):
                var script = ""
                for (predictor, term) in zip(predictors, terms.dropFirst()) where predictor.isCategorical {
                    let level = predictor.referenceLevel.map { ", ref = \(Self.quote($0))" } ?? ""
                    script += "d$\(term.name) <- relevel(factor(d$\(term.name))\(level))\n"
                }
                let formula = "\(names[0]) ~ " + names.dropFirst().joined(separator: " + ")
                script += """
                model <- lm(\(formula), data = d)
                print(summary(model))
                print(confint(model))
                print(anova(model))
                # Beyond what the notebook reports:
                # car::vif(model)        # generalized VIF, correct for multi-level factors
                # plot(model)            # residual diagnostics
                # lmtest::dwtest(model)  # autocorrelation

                """
                return script
        }
    }

    private static func quote(_ text: String) -> String {
        "\"" + text.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }
}
